### PR TITLE
Update to latest ember-cli

### PR DESCRIPTION
**Pull request by bcardarella**

### CODE REVIEW

**Comment by bcardarella** [comment]
this passes with in-browser tests but not on the command line... investigating

**Comment by seawatts** [comment]
@bcardarella any progress on this? Looks like this is now behind on versions too. Might want to bump it to 1.13.0 for ember and 0.2.7 for ember-cli

**Comment by williamsbdev** [comment]
Has this made any progress on the upgrade of ember-cli?

**Comment by williamsbdev** [comment]
I believe this PR would/could be closed by merging #56.

**Pull request closed without merging**
