### PR TITLE
Upgrades Ember and CLI version and utilizes positional parameters

### PR DESCRIPTION
**Pull request by danmcclain**
Positional parameters (introduced in 1.13) remove the need for the helper to pass "bare" arguments to a component.

Brings in ember-try via Ember CLI upgrade

**Note:** I was planning on leaving the positional params update to a separate PR but it was required to remove deprecation warnings. I can break out that work to a separate PR if required

### CODE REVIEW

**Comment by danmcclain** [comment]
I'm going to rework this so that it doesn't break version less than `1.13`, and add a earlier version to ember-try

**Comment by bcardarella** [comment]
If it means having conditionals everywhere to support older versions I
would prefer not to do that. Simply tell people to use the older version if
they aren't on 1.13+

On Sunday, June 21, 2015, Dan McClain <notifications@github.com> wrote:

> I'm going to rework this so that it doesn't break version less than 1.13,
> and add a earlier version to ember-try
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dockyard/ember-cli-async-button/pull/51#issuecomment-113940990>
> .
>


-- 

----------------------
Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

**Comment by danmcclain** [comment]
@bcardarella I thought we were passed `1.0.0`, the code would introduce one conditional, if you are fine with rev'ing the minor version, we could avoid the pre `1.13` support :+1: 

Also, the only test failures are with the `2.0.0-beta` now

**Comment by danmcclain** [comment]
Tests are now passing

**Comment by danmcclain** [comment]
@bcardarella Good to merge?

**Comment by bcardarella** [comment]
:+1:

**Pull request merged**
