### PR TITLE
Use Ember Suave

### PR DESCRIPTION
**Pull request by duggiefresh**

### CODE REVIEW

**Comment by duggiefresh** [comment]
Y U PASS LOCALLY?

**Comment by rwjblue** [comment]
Make sure you `nom` (aka `rm -rf node_modules && npm cache clear && npm install`) to get the latest JSCS/ember-suave versions locally.

**Comment by duggiefresh** [comment]
+1 First thing I did and was able to reproduce errors.

**Comment by bcardarella** [comment]
RE-RE-RE-REBASE!

**Pull request closed without merging**
